# Generated by Django 4.0.6 on 2022-09-07 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('price', models.FloatField()),
                ('discount', models.FloatField(blank=True, null=True)),
                ('stock', models.CharField(max_length=300)),
                ('colors', models.TextField()),
                ('description', models.TextField()),
                ('brand', models.ManyToManyField(related_name='brand', to='shop.brand')),
                ('category', models.ManyToManyField(related_name='category', to='shop.category')),
            ],
        ),
    ]
